#!/usr/bin/env python3
"""Split the pinned Symbols Nerd Font Mono TTF into character-loaded WOFF2 files.

Requires fontTools and the woff2_compress CLI. No network access is performed.
Usage: python3 tools/subset-nerd-font.py /path/to/SymbolsNerdFontMono-Regular.ttf
"""

import argparse
import hashlib
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "source/css/font"
START = "/* #region Nerd Font subsets (generated by tools/subset-nerd-font.py) */"
END = "/* #endregion Nerd Font subsets */"
MAX_BYTES = 64 * 1024
SOURCE_SHA256 = "f0f624d9b474bea1662cf7e862d44aebe1ae1f6c7f9cb7a0ca5d0e5ac9561c60"


def unicode_ranges(codepoints):
    runs = []
    for codepoint in sorted(codepoints):
        if runs and codepoint == runs[-1][1] + 1:
            runs[-1][1] = codepoint
        else:
            runs.append([codepoint, codepoint])
    return ", ".join(f"U+{first:X}" if first == last else f"U+{first:X}-{last:X}" for first, last in runs)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("ttf", type=Path)
    parser.add_argument("--compressor", default="woff2_compress")
    args = parser.parse_args()
    source = args.ttf.resolve()
    if hashlib.sha256(source.read_bytes()).hexdigest() != SOURCE_SHA256:
        raise ValueError("Expected the upstream Nerd Fonts v3.4.0 SymbolsNerdFontMono-Regular.ttf")
    with TTFont(source) as font:
        all_codepoints = set(font.getBestCmap())
    common = {
        int(line.split("#")[0].strip(), 16)
        for line in (FONT_DIR / "nerd-font-common.txt").read_text().splitlines()
        if line.split("#")[0].strip()
    }
    if not common <= all_codepoints:
        raise ValueError("The source font is missing common glyphs")

    groups = {}
    for codepoint in sorted(all_codepoints - common):
        groups.setdefault(codepoint // 256, []).append(codepoint)

    css_path = ROOT / "source/css/default.css"
    css = css_path.read_text()
    start = css.index(START)
    end = css.index(END, start) + len(END)
    old_files = set(re.findall(r'font/woff2/(SymbolsNerdFontMono-[^"/]+\.woff2)', css[start:end]))
    records = []
    covered = set()

    with tempfile.TemporaryDirectory(prefix="gnix-nerd-font-") as temporary:
        build_dir = Path(temporary)

        def build(name, codepoints):
            codepoints = sorted(codepoints)
            ttf_path = build_dir / f"{name}.ttf"
            options = subset.Options()
            options.name_IDs = ["*"]
            options.name_languages = ["*"]
            options.recalc_timestamp = False
            options.drop_tables.append("PfEd")
            with TTFont(source, recalcTimestamp=False) as font:
                subsetter = subset.Subsetter(options=options)
                subsetter.populate(unicodes=codepoints)
                subsetter.subset(font)
                if set(font.getBestCmap()) != set(codepoints):
                    raise ValueError(f"Unexpected character coverage in {name}")
                font.save(ttf_path)
            subprocess.run([args.compressor, str(ttf_path)], check=True, capture_output=True)
            woff2_path = ttf_path.with_suffix(".woff2")
            data = woff2_path.read_bytes()
            if len(data) > MAX_BYTES and len(codepoints) > 1:
                midpoint = len(codepoints) // 2
                build(f"{name}-a", codepoints[:midpoint])
                build(f"{name}-b", codepoints[midpoint:])
                return
            if covered.intersection(codepoints):
                raise ValueError(f"Overlapping Unicode range in {name}")
            covered.update(codepoints)
            digest = hashlib.sha256(data).hexdigest()[:8]
            filename = f"SymbolsNerdFontMono-{name}.{digest}.woff2"
            records.append((filename, unicode_ranges(codepoints), len(codepoints), len(data), woff2_path))

        build("common", common)
        for block, codepoints in groups.items():
            build(f"u{block * 256:04x}", codepoints)
        if covered != all_codepoints:
            raise ValueError("The shards must retain complete upstream character coverage")

        faces = [START]
        for filename, ranges, _, _, file in records:
            shutil.copyfile(file, FONT_DIR / "woff2" / filename)
            faces.append(f'''@font-face {{
  font-family: "Symbols Nerd Font Mono";
  src: url("font/woff2/{filename}") format("woff2");
  font-style: normal;
  font-weight: 400;
  font-display: block;
  unicode-range: {ranges};
}}''')
        faces.append(END)
        css_path.write_text(css[:start] + "\n\n".join(faces) + css[end:])
        filenames = {record[0] for record in records}
        for filename in old_files - filenames:
            (FONT_DIR / "woff2" / filename).unlink(missing_ok=True)

    print(f"{len(records)} shards, {len(covered)} characters, {sum(record[3] for record in records):,} bytes total")
    for filename, _, count, size, _ in records:
        print(f"{filename}: {count} characters, {size:,} bytes")


if __name__ == "__main__":
    main()
